import { defineCommand } from "citty";
import { getPackageMeta, listPackages } from "../lib/pkg.ts";
import { ASSETS } from "../assets/definitions.ts";
import { logError } from "../lib/console.ts";
// Import cycle with registry.ts — safe because REGISTRY is only accessed
// inside generateZsh() at command time, never at module top level.
import { REGISTRY } from "./registry.ts";

async function collectTags(pkgs: string[]): Promise<string[]> {
  const tags = new Set<string>();
  for (const name of pkgs) {
    const meta = await getPackageMeta(name);
    if (meta) for (const tag of meta.tags) tags.add(tag);
  }
  return [...tags].sort();
}

// Build `_describe` entries ('name:description') from a citty subCommands map,
// so completion lists stay in sync with the real command tree.
function describeEntries(cmds: Record<string, unknown>, indent: string): string[] {
  return Object.entries(cmds).map(([name, cmd]) => {
    const meta = (cmd as { meta?: { description?: string } }).meta;
    const desc = (meta?.description ?? "").replace(/'/g, "");
    return `${indent}'${name}:${desc}'`;
  });
}

async function generateZsh(): Promise<string> {
  const packages = await listPackages();
  const tags = await collectTags(packages);
  const assetNames = ASSETS.map((a) => a.name);
  const date = new Date().toISOString().split("T")[0];

  const pkgList = packages.join(" ");
  const tagList = tags.join(" ");
  const assetList = assetNames.join(" ");

  // Written as string array (not template literal) so $-prefixed zsh variables
  // are never misread as TypeScript interpolations.
  const lines: string[] = [
    "#compdef dot",
    `# Generated by: dot completions zsh  (${date})`,
    "# Install: dot completions zsh > ~/.zsh/completions/_dot",
    "#          Then restart your shell or run: compinit",
    "",
    "_dot() {",
    "  local curcontext=\"$curcontext\" state line",
    "  typeset -A opt_args",
    "  _arguments -C \\",
    "    '1: :->cmd' \\",
    "    '*:: :->args' && return 0",
    "",
    "  case $state in",
    "    cmd)",
    "      local -a subcmds",
    "      subcmds=(",
    ...describeEntries(REGISTRY, "        "),
    "      )",
    "      _describe 'subcommand' subcmds",
    "      ;;",
    "    args)",
    "      case $line[1] in",
    "        pkg)         _dot_pkg ;;",
    "        update)      _dot_update ;;",
    "        assets)      _dot_assets ;;",
    "        tools)       _dot_tools ;;",
    "        doctor)      _dot_doctor ;;",
    "        completions) _dot_completions ;;",
    "      esac",
    "      ;;",
    "  esac",
    "}",
    "",
    "_dot_pkg() {",
    `  local -a packages=(${pkgList})`,
    `  local -a tags=(${tagList})`,
    "",
    "  _arguments \\",
    "    '--init=[Init system]:init:(runit systemd launchd)' \\",
    "    '--dry-run[Preview without applying]' \\",
    "    '--force[Allow overwriting real files]' \\",
    "    '--ignore-host[Link even if excluded by host filter]' \\",
    "    \"--tag=[Apply action to all packages with this tag]:tag:($tags)\" \\",
    "    '-y[Skip unlink confirmation]' \\",
    "    '--yes[Skip unlink confirmation]' \\",
    "    '1: :->pkg_or_action' \\",
    "    '2: :->action'",
    "",
    "  case $state in",
    "    pkg_or_action)",
    "      _alternative \\",
    "        \"packages:package:($packages)\" \\",
    "        'special:special action:(status)'",
    "      ;;",
    "    action)",
    "      local -a actions=(info link unlink status configure enable disable)",
    "      _values 'action' $actions",
    "      ;;",
    "  esac",
    "}",
    "",
    "_dot_update() {",
    "  _arguments -C \\",
    "    '--all[Run system + global + source]' \\",
    "    '--check[Show what would update without making changes]' \\",
    "    '--info[Show installed versions]' \\",
    "    '--ai[Analyse output with AI after completion]' \\",
    "    '1: :->subcmd'",
    "",
    "  if [[ $state == subcmd ]]; then",
    "    local -a subcmds=(",
    "      'system:Update system packages (xbps/pacman+yay/brew, flatpak, bun, deno, rustup)'",
    "      'global:Update global package manager packages (npm, bun, pipx, cargo...)'",
    "      'source:Update source/custom-built tools (pkgbuilds, fnm, anyzig, ly, zinit)'",
    "    )",
    "    _describe 'subcommand' subcmds",
    "  fi",
    "}",
    "",
    "_dot_assets() {",
    `  local -a asset_names=(${assetList})`,
    "",
    "  _arguments -C \\",
    "    '1: :->subcmd' \\",
    "    '2: :->asset'",
    "",
    "  case $state in",
    "    subcmd)",
    "      local -a subcmds=(",
    "        'list:Show all assets with installed and latest versions'",
    "        'sync:Download/update all assets, or a specific one'",
    "        'info:Show details for a specific asset'",
    "        'test:Test font installation and Unicode rendering'",
    "      )",
    "      _describe 'subcommand' subcmds",
    "      ;;",
    "    asset)",
    "      if [[ $line[1] == (sync|info|test) ]]; then",
    "        _values 'asset' $asset_names",
    "      fi",
    "      ;;",
    "  esac",
    "}",
    "",
    "_dot_tools() {",
    "  _arguments -C \\",
    "    '1: :->subcmd'",
    "",
    "  if [[ $state == subcmd ]]; then",
    "    local -a subcmds=(",
    ...describeEntries((REGISTRY.tools as { subCommands?: Record<string, unknown> }).subCommands ?? {}, "      "),
    "    )",
    "    _describe 'subcommand' subcmds",
    "  fi",
    "}",
    "",
    "_dot_doctor() {",
    "  _arguments \\",
    "    '(-v --verbose)-v[Show details for every package]' \\",
    "    '(-v --verbose)--verbose[Show details for every package]' \\",
    "    '(-q --quiet)-q[Suppress per-package output]' \\",
    "    '(-q --quiet)--quiet[Suppress per-package output]' \\",
    "    '--all-hosts[Check packages from all hosts]' \\",
    "    '--fix[Repair broken symlinks and re-link partially-linked packages]' \\",
    "    '--force[With --fix, overwrite real files (drift)]'",
    "}",
    "",
    "_dot_completions() {",
    "  _arguments \\",
    "    '1: :->shell'",
    "",
    "  if [[ $state == shell ]]; then",
    "    _values 'shell' 'zsh'",
    "  fi",
    "}",
    "",
    "_dot",
    "",
  ];

  return lines.join("\n");
}

export const completionsCommand = defineCommand({
  meta: { description: "Generate shell completion scripts" },
  async run({ rawArgs }) {
    const shell = rawArgs.find((a) => !a.startsWith("-")) ?? "zsh";

    if (shell !== "zsh") {
      logError(`Unsupported shell: ${shell}. Currently supported: zsh`);
      process.exit(1);
    }

    process.stdout.write(await generateZsh());
  },
});
