#!/usr/bin/env bash
# Install the TypeScript 7 native (Go) language server that ~/.omp/agent/lsp.json pins.
#
# ── Why a private prefix and not the system package ─────────────────────────────────
# Arch `extra/typescript` is 6.0.3, whose LSP path is node: typescript-language-server
# forks a tsserver child that holds the whole program graph in a V8 heap. Measured on
# /data/code/fleet (751 TS files, 924 MiB node_modules), hover + references from a cold
# start: 900 MiB PSS across 4 processes. The same probe against `tsc --lsp --stdio` from
# TypeScript 7.0.2: 308 MiB in 1 process. Every agent session pays that difference, and
# this box runs five or more at once.
#
# The install lives in ~/.local/share/typescript-native rather than on PATH so that
# `tsc` keeps meaning 6.0.3 for builds — fleet still declares typescript ^6.0.0 and
# typechecks with it. Only omp's language server is moved.
#
# ── Why the .bin/tsc path in lsp.json and not the raw Go binary ─────────────────────
# omp decides between `typescript-native` and `typescript-language-server` by walking up
# from the server's resolved command to a typescript package dir and testing for
# lib/tsserver.js (absent => TS7 => native wins). That walk only recognises a real npm
# layout: a `bin/` parent, ../typescript, or ./node_modules/typescript. Pointing straight
# at @typescript/typescript-linux-x64/lib/tsc defeats it and the native server is dropped.
# node_modules/.bin/tsc resolves correctly, and costs nothing: TS7's launcher calls
# process.execve (node >= 22.15), so node replaces itself with the Go binary rather than
# staying resident as a parent.
#
# ── Removing this ───────────────────────────────────────────────────────────────────
# Delete ~/.local/share/typescript-native and the `typescript-native` block from
# packages/omp/home/.omp/agent/lsp.json. omp falls back to typescript-language-server,
# which is still heap-capped by the shim at ~/.local/bin/typescript-language-server.
set -euo pipefail

PREFIX="$HOME/.local/share/typescript-native"
WANT="${TYPESCRIPT_NATIVE_VERSION:-7.0.2}"

have=""
if [ -f "$PREFIX/node_modules/typescript/package.json" ]; then
  have=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' \
    "$PREFIX/node_modules/typescript/package.json" 2>/dev/null || true)
fi

if [ "$have" = "$WANT" ]; then
  echo "typescript-native $WANT already installed at $PREFIX"
else
  mkdir -p "$PREFIX"
  [ -f "$PREFIX/package.json" ] ||
    echo '{"name":"typescript-native-lsp","private":true}' >"$PREFIX/package.json"
  npm install --prefix "$PREFIX" --no-audit --no-fund "typescript@$WANT" >/dev/null
  echo "typescript-native $WANT installed at $PREFIX"
fi

# The npm entrypoint must exist, and must be the TS7 install — a stale TS6 copy here
# would make omp silently fall back to the node server.
bin="$PREFIX/node_modules/.bin/tsc"
[ -x "$bin" ] || {
  echo "missing $bin" >&2
  exit 1
}
[ -f "$PREFIX/node_modules/typescript/lib/tsserver.js" ] &&
  {
    echo "$PREFIX holds a TypeScript <= 6 install; omp would keep using tsserver" >&2
    exit 1
  }

# ── The heap ceiling ────────────────────────────────────────────────────────────────
# The Go server has no --max-old-space-size, and its working set does grow under a real
# editing session: 150 fleet files opened, edited and closed, three passes, measured
# 739 -> 943 -> 1091 MiB with a 1205 MiB peak (it does give memory back — 780 MiB once
# idle, versus the node stack which ended that same run at 2155 MiB and still climbing).
# typescript-go#3032 is the unbounded tail of that curve: closed for lack of a repro, but
# one reporter saw 50 GB, so it is worth a bound rather than a bet.
#
# GOMEMLIMIT is the Go analogue of the V8 flag — a soft limit that makes the collector
# work harder instead of letting the heap run. The same three-pass probe under
# GOMEMLIMIT=700MiB stayed flat: 653 -> 615 -> 610 MiB, 659 MiB peak, no slower.
# 1536 MiB leaves comfortable headroom over the 780 MiB idle working set.
#
# It has to be a wrapper because ServerConfig has no `env` field. The wrapper lives in a
# `bin/` dir with a package.json one level up so that omp's install walk still classifies
# it as a TypeScript 7 install (bin parent -> ../, no lib/tsserver.js). It is written
# outside node_modules so that reinstalling typescript cannot drop it.
mkdir -p "$PREFIX/lsp/bin"
cat >"$PREFIX/lsp/package.json" <<'EOF'
{ "name": "typescript-native-lsp-wrapper", "private": true, "bin": { "tsc": "bin/tsc" } }
EOF
cat >"$PREFIX/lsp/bin/tsc" <<EOF
#!/usr/bin/env bash
# Generated by packages/omp/configure.sh — edit that, not this.
set -euo pipefail
export GOMEMLIMIT="\${TSGO_MEM_LIMIT:-1536MiB}"
exec "$PREFIX/node_modules/.bin/tsc" "\$@"
EOF
chmod +x "$PREFIX/lsp/bin/tsc"

# ── Why lsp.json says `tsgo-lsp` and not a path ─────────────────────────────────────
# A JSON config cannot hold $HOME, and omp does not expand `~` in `command` — a tilde
# path resolves to nothing and omp silently falls back to typescript-language-server,
# which looks identical until you check `lsp action=status`. A bare name is resolved
# through PATH instead, so the versioned file stays user-agnostic.
#
# The symlink target matters: omp's install walk realpaths the command before looking
# for the `bin/` parent, so ~/.local/bin/tsgo-lsp resolves to $PREFIX/lsp/bin/tsc and
# lands on $PREFIX/lsp, which is exactly the layout built above.
mkdir -p "$HOME/.local/bin"
ln -sfn "$PREFIX/lsp/bin/tsc" "$HOME/.local/bin/tsgo-lsp"

tsgo-lsp --version
